### ISSUE TITLE
rake db:setup throws "Tried to load unspecified class: Documentation"

### ISSUE THREAD

**Issue by zackw** [berkmancenter/tagteam#36]
I'm trying to initialize my own instance of tagteam.  I've gotten as far as the database setup phase, and I get this error:

```
$ export RAILS_ENV=production
$ rake --trace db:setup
** Invoke db:setup (first_time)
** Invoke db:schema:load_if_ruby (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
Created database 'tagteam_production'
** Invoke environment (first_time)
** Execute environment
** Execute db:schema:load_if_ruby
** Invoke db:schema:load (first_time)
** Invoke environment 
** Invoke db:load_config 
** Invoke db:check_protected_environments (first_time)
** Invoke environment 
** Invoke db:load_config 
** Execute db:check_protected_environments
** Execute db:schema:load
-- enable_extension("plpgsql")
   -> 0.0106s
-- create_table("deactivated_taggings", {:force=>:cascade})
   -> 0.0346s
-- create_table("documentations", {:force=>:cascade})
   -> 0.0288s
-- create_table("feed_items", {:force=>:cascade})
   -> 0.0308s
-- create_table("feed_items_feed_retrievals", {:id=>false, :force=>:cascade})
   -> 0.0128s
-- create_table("feed_items_feeds", {:id=>false, :force=>:cascade})
   -> 0.0184s
-- create_table("feed_retrievals", {:force=>:cascade})
   -> 0.0145s
-- create_table("feed_subscribers", {:force=>:cascade})
   -> 0.0227s
-- create_table("feed_visitors", {:force=>:cascade})
   -> 0.0113s
-- create_table("feeds", {:force=>:cascade})
   -> 0.0429s
-- create_table("friendly_id_slugs", {:force=>:cascade})
   -> 0.0292s
-- create_table("hub_feeds", {:force=>:cascade})
   -> 0.0328s
-- create_table("hub_user_notifications", {:force=>:cascade})
   -> 0.0147s
-- create_table("hubs", {:force=>:cascade})
   -> 0.0293s
-- create_table("input_sources", {:force=>:cascade})
   -> 0.0440s
-- create_table("republished_feeds", {:force=>:cascade})
   -> 0.0275s
-- create_table("roles", {:force=>:cascade})
   -> 0.0248s
-- create_table("roles_users", {:id=>false, :force=>:cascade})
   -> 0.0145s
-- create_table("search_remixes", {:force=>:cascade})
   -> 0.0062s
-- create_table("tag_filters", {:force=>:cascade})
   -> 0.0513s
-- create_table("taggings", {:force=>:cascade})
   -> 0.0708s
-- create_table("tags", {:force=>:cascade})
   -> 0.0218s
-- create_table("users", {:force=>:cascade})
   -> 0.0465s
-- initialize_schema_migrations_table()
   -> 0.0069s
** Invoke db:structure:load_if_sql (first_time)
** Invoke db:create 
** Invoke environment 
** Execute db:structure:load_if_sql
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment 
** Invoke db:load_config 
** Execute db:abort_if_pending_migrations
rake aborted!
Psych::DisallowedClass: Tried to load unspecified class: Documentation
/usr/lib/ruby/2.3.0/psych/class_loader.rb:97:in `find'
/usr/lib/ruby/2.3.0/psych/class_loader.rb:28:in `load'
/usr/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:396:in `resolve_class'
/usr/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
/usr/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
/usr/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
/usr/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
/usr/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `block in register_empty'
/usr/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `each'
/usr/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `register_empty'
/usr/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:141:in `visit_Psych_Nodes_Sequence'
/usr/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
/usr/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
/usr/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
/usr/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
/usr/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
/usr/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
/usr/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
/usr/lib/ruby/2.3.0/psych.rb:304:in `safe_load'
/home/tagteam/tagteam/db/seeds.rb:16:in `<top (required)>'
/home/tagteam/tagteam/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:287:in `load'
/home/tagteam/tagteam/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:287:in `block in load'
/home/tagteam/tagteam/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/tagteam/tagteam/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:287:in `load'
/home/tagteam/tagteam/vendor/bundle/ruby/2.3.0/gems/railties-5.0.3/lib/rails/engine.rb:549:in `load_seed'
/home/tagteam/tagteam/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/tasks/database_tasks.rb:270:in `load_seed'
/home/tagteam/tagteam/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/railties/databases.rake:184:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:165:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:150:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:115:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:100:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:78:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/bin/rake:27:in `<main>'
```

Line 16 of `db/seeds.rb` reads

``` ruby
docs = YAML.safe_load(File.read("#{Rails.root}/db/documentation.yml"))
```

and I see that `db/documentation.yml` appears to be intentionally instantiating Documentation objects, but I have no idea how to make `YAML.safe_load` willing to do that.  (I have zero Ruby experience.)

**Comment by peter-hank** [comment]
Hi @zackw,

sorry about that. It has something to do with a migration to Rails 5 that has happened recently.

We will try to fix this issue with a new release. If you want to use the application earlier try to comment it out for now so `db/seeds.rb` looks like this:

```ruby
require 'yaml'
require 'digest/md5'

#Documentation.destroy_all
#docs = YAML.safe_load(File.read("#{Rails.root}/db/documentation.yml"))
#docs.each do |doc_attr|
# d = Documentation.find_or_initialize_by(match_key: doc_attr.attributes[:match_key])
#  d.attributes = doc_attr.attributes
#  d.id = nil
#  d.save
#end
```

**Comment by zackw** [comment]
Thanks, this workaround has advanced me to a new problem (for which I will file a new issue). This appears to skip loading the online help into the database? Will it be possible to load it manually, after the bug is fixed, or will I have to drop and recreate the database?

**Comment by peter-hank** [comment]
@zackw yes, it will be possible.

You will just need to run:
```bash
$ bundle exec db:seed
```
